### PR TITLE
want to get the new-homepage up to date with main so I can push to main

### PR DESCRIPTION
**Pull request by Iqmaa**

### CODE REVIEW

**Comment by EmmanuelPetrus** [comment]
Alright, boss lady. You're good to go

**Comment by mirera** [comment]
Pee have you gone through the code on your local machine.

**Comment by EmmanuelPetrus** [comment]
Yes, I've reviewed her code on my local machine. However, I pointed out some things for her to change. kindly halt the merging for now. I'll send a pull request when those changes have been effected. Thanks

**Comment by mirera** [comment]
We have agreed with her she will do a new PR. I am closing this one. Thanks emmy

**Pull request closed without merging**
